name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04-x64 # Aquí usas el runner auto-hospedado
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Paso para instalar Ruby en el runner auto-hospedado
      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libreadline-dev zlib1g-dev

          # Instalar rbenv y ruby-build
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc

          # Instalar Ruby 3.1.4
          ~/.rbenv/bin/rbenv install 3.1.4
          ~/.rbenv/bin/rbenv global 3.1.4

          # Verifica que Ruby esté instalado correctamente
          ruby -v

      - name: Setup Bundler and Install Gems
        run: |
          gem install bundler
          bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-x64
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
